### ISSUE TITLE
Illegal state use in component code

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#2127]
**Describe the bug**

A discord user reported seeing the following message:
```
 Caused by:
invalid chain parameters: slashing penalty (misbehavior) must be at most 10,000 basis points, proposal pass threshold must be greater than 1/2 elapsed=10.950259ms
2023-03-09T13:36:36.328077Z  INFO abci:BeginBlock{height=38997}: beginning block time=Time(2023-03-09 13:36:30.150306536)
2023-03-09T13:36:36.341884Z  INFO abci:DeliverTx{txid="bd7c889dd9c5d92acff30ef0a4b5d8994bad969f47b69bb5e50651b2427363ab"}: deliver_tx failed e=invalid change to chain parameters
thread 'tokio-runtime-worker' panicked at 'state Arc should not be referenced elsewhere', /usr/src/component/src/app/mod.rs:203:14
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: consensus worker terminated or panicked', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tower-abci-0.5.0/src/server.rs:145:70
```

Regardless of whatever's happening with the chain parameters, the `state Arc should not be referenced elsewhere` message indicates a serious bug related to the way state handles are passed through the component code.

The panic references line 203, which is here: https://github.com/penumbra-zone/penumbra/blob/main/component/src/app/mod.rs#L203

This is at the beginning of `end_block`. So something is holding a reference to the app's `state` into the beginning of `end_block`.

**Comment by gitn17** [comment]
well it turns out i was on 047-sinope branch, not the 047-sinope.1
anyway originally there was long repeated cycle of "caused by" msg, wich end up with:

```
penumbra-node0    | Caused by:
penumbra-node0    |     invalid chain parameters: slashing penalty (misbehavior) must be at most 10,000 basis points, proposal pass threshold must be greater than 1/2 elapsed=12.53922ms
penumbra-node0    | 2023-03-09T13:36:35.636868Z  INFO abci:CheckTx{kind=New txid="bd7c889dd9c5d92acff30ef0a4b5d8994bad969f47b69bb5e50651b2427363ab"}: tx rejected e=invalid change to chain parameters
penumbra-node0    |
penumbra-node0    | Caused by:
penumbra-node0    |     invalid chain parameters: slashing penalty (misbehavior) must be at most 10,000 basis points, proposal pass threshold must be greater than 1/2 elapsed=10.950259ms
penumbra-node0    | 2023-03-09T13:36:36.328077Z  INFO abci:BeginBlock{height=38997}: beginning block time=Time(2023-03-09 13:36:30.150306536)
penumbra-node0    | 2023-03-09T13:36:36.341884Z  INFO abci:DeliverTx{txid="bd7c889dd9c5d92acff30ef0a4b5d8994bad969f47b69bb5e50651b2427363ab"}: deliver_tx failed e=invalid change to chain parameters
penumbra-node0    |
penumbra-node0    | Caused by:
penumbra-node0    |     invalid chain parameters: slashing penalty (misbehavior) must be at most 10,000 basis points, proposal pass threshold must be greater than 1/2
penumbra-node0    | thread 'tokio-runtime-worker' panicked at 'state Arc should not be referenced elsewhere', /usr/src/component/src/app/mod.rs:203:14
penumbra-node0    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
penumbra-node0    | thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: consensus worker terminated or panicked', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tower-abci-0.5.0/src/server.rs:145:70
```

after resync had this

```
tendermint-node0  | I[2023-03-09|16:14:30.530] committed state                              module=state height=38995 num_txs=0 app_hash=EED807BF3F85D83C6A86F1716C8CB491A57E760A48510FB5B442107D3B32328C
tendermint-node0  | I[2023-03-09|16:14:30.542] indexed block exents                         module=txindex height=38995
penumbra-node0    | 2023-03-09T16:14:30.605098Z  INFO abci:BeginBlock{height=38996}: beginning block time=Time(2023-03-09 13:36:24.376045361)
tendermint-node0  | I[2023-03-09|16:14:30.623] executed block                               module=state height=38996 num_valid_txs=0 num_invalid_txs=0
tendermint-node0  | I[2023-03-09|16:14:30.624] service start                                module=p2p peer=30a99e30cf662d3e29ab9b55ef18049b7efb5487@35.226.255.25:26656 msg="Starting Peer service" impl=                              "Peer{MConn{35.226.255.25:26656} 30a99e30cf662d3e29ab9b55ef18049b7efb5487 out}"
tendermint-node0  | I[2023-03-09|16:14:30.624] service start                                module=p2p peer=30a99e30cf662d3e29ab9b55ef18049b7efb5487@35.226.255.25:26656 msg="Starting MConnection service                              " impl=MConn{35.226.255.25:26656}
tendermint-node0  | I[2023-03-09|16:14:30.625] Added peer                                   module=p2p peer="Peer{MConn{35.226.255.25:26656} 30a99e30cf662d3e29ab9b55ef18049b7efb5487 out}"
penumbra-node0    | 2023-03-09T16:14:30.649595Z  INFO abci:Commit: committed block app_hash=AppHash("ed2e7a5d4f7fbc89b1e9488ee2038567f7a4b953812fbc276337fda15f7ccb9b")
tendermint-node0  | I[2023-03-09|16:14:30.649] committed state                              module=state height=38996 num_txs=0 app_hash=ED2E7A5D4F7FBC89B1E9488EE2038567F7A4B953812FBC276337FDA15F7CCB9B
tendermint-node0  | I[2023-03-09|16:14:30.690] indexed block exents                         module=txindex height=38996
penumbra-node0    | 2023-03-09T16:14:30.735105Z  INFO abci:BeginBlock{height=38997}: beginning block time=Time(2023-03-09 13:36:30.150306536)
penumbra-node0    | 2023-03-09T16:14:30.751140Z  INFO abci:DeliverTx{txid="bd7c889dd9c5d92acff30ef0a4b5d8994bad969f47b69bb5e50651b2427363ab"}: deliver_tx failed e=invalid change to chain parameters
penumbra-node0    |
penumbra-node0    | Caused by:
penumbra-node0    |     invalid chain parameters: slashing penalty (misbehavior) must be at most 10,000 basis points, proposal pass threshold must be greater than 1/2
tendermint-node0  | I[2023-03-09|16:14:30.762] executed block                               module=state height=38997 num_valid_txs=0 num_invalid_txs=1
penumbra-node0    | 2023-03-09T16:14:30.791731Z  INFO abci:Commit: committed block app_hash=AppHash("c80f95cf9b4b4e1cda4c5032225775f6afd5ede3b23c5e93e5eb1bb194501220")
tendermint-node0  | I[2023-03-09|16:14:30.834] committed state                              module=state height=38997 num_txs=1 app_hash=C80F95CF9B4B4E1CDA4C5032225775F6AFD5EDE3B23C5E93E5EB1BB194501220
tendermint-node0  | I[2023-03-09|16:14:30.852] Connection is closed @ recvRoutine (likely by the other side) module=p2p peer=30a99e30cf662d3e29ab9b55ef18049b7efb5487@35.226.255.25:26656 conn=MConn{35.22                              6.255.25:26656}
tendermint-node0  | I[2023-03-09|16:14:30.852] service stop                                 module=p2p peer=30a99e30cf662d3e29ab9b55ef18049b7efb5487@35.226.255.25:26656 msg="Stopping MConnection service                              " impl=MConn{35.226.255.25:26656}
tendermint-node0  | E[2023-03-09|16:14:30.852] Stopping peer for error                      module=p2p peer="Peer{MConn{35.226.255.25:26656} 30a99e30cf662d3e29ab9b55ef18049b7efb5487 out}" err=EOF
tendermint-node0  | I[2023-03-09|16:14:30.852] service stop                                 module=p2p peer=30a99e30cf662d3e29ab9b55ef18049b7efb5487@35.226.255.25:26656 msg="Stopping Peer service" impl=                              "Peer{MConn{35.226.255.25:26656} 30a99e30cf662d3e29ab9b55ef18049b7efb5487 out}"
tendermint-node0  | I[2023-03-09|16:14:30.852] Reconnecting to peer                         module=p2p addr=30a99e30cf662d3e29ab9b55ef18049b7efb5487@35.226.255.25:26656
tendermint-node0  | I[2023-03-09|16:14:30.852] Dialing peer                                 module=p2p address=30a99e30cf662d3e29ab9b55ef18049b7efb5487@35.226.255.25:26656
tendermint-node0  | I[2023-03-09|16:14:30.860] indexed block exents                         module=txindex height=38997
tendermint-node0  | E[2023-03-09|16:14:30.863] Error in validation                          module=blockchain err="wrong Block.Header.AppHash.  Expected C80F95CF9B4B4E1CDA4C5032225775F6AFD5EDE3B23C5E93E                              5EB1BB194501220, got D8DA4AD1A18ACA051DAE2C5DBD7BC51B78FE561A2D1D183EFB37B050D4FF630A"
tendermint-node0  | E[2023-03-09|16:14:30.864] Stopping peer for error                      module=p2p peer="Peer{MConn{89.117.59.200:26656} b05590ed275941611be6e41f1b7c421dde9b83c1 out}" err="blockchai                              nReactor validation error: wrong Block.Header.AppHash.  Expected C80F95CF9B4B4E1CDA4C5032225775F6AFD5EDE3B23C5E93E5EB1BB194501220, got D8DA4AD1A18ACA051DAE2C5DBD7BC51B78FE561A2D1D183EFB37B050D4FF630A"
```
the lesson is to patienly wait for update announcement, or doublecheck branch at least.
