### ISSUE TITLE
ibc: go-relayer doesn't work on Penumbra v0.62.0

### ISSUE THREAD

**Issue by conorsch** [penumbra-zone/penumbra#3222]
**Describe the bug**
The [go relayer](https://github.com/cosmos/relayer) cannot make IBC transfers between Penumbra and Cosmos local devnets as of v0.62.0. When testing with v0.61.0 (and the required CometBFT v0.34.27), the IBC tests in [interchaintest](https://github.com/strangelove-ventures/interchaintest) pass. I suspect there's a regression in the query results between releases. 

**To Reproduce**

1. Check out the [relayer](https://github.com/cosmos/relayer), specifically the `justin/ibc-v8` branch.
2. Build a local container for the relayer: `docker build -t relayer:local .`
3. Check out [interchaintest](https://github.com/strangelove-ventures/interchaintest), specifically the `justin/penumbra-ibc` branch.
4. Run the IBC test suite: `go test -v examples/penumbra/penumbra_ibc_test.go` (N.B. golang >= v1.20 is required)

**Expected behavior**

**Screenshots**

**Additional context**
The relevant relayer logic can be found here: https://github.com/cosmos/relayer/blob/d0deac591ef987a702f4d9a6a0cb5629a53824cc/relayer/chains/penumbra/tx.go#L249-L276

<details>
<summary>
relayer error output
</summary>

```
 penumbra_ibc_test.go:92: 
        	Error Trace:	/Users/justintieri/go/src/github.com/strangelove-ventures/interchaintest/examples/penumbra/penumbra_ibc_test.go:92
        	Error:      	Received unexpected error:
        	            	failed to link path ab on relayer &{%!s(*relayer.DockerRelayer=&{0x14001426540 0x140001f6000 581b5cb24d62edfd07d5069b816445d55d4c940a77a38700d3c5cf1402dedb28 0x140013fab00 765acff6da999ad18d7ba5067115a0165277662ebb854acb3dd73f90dc7f64e9 TestPenumbraToPenumbraIBC 0x140015bbb30 false <nil> map[penumbraA-0:0x140014eb7d0 penumbraB-0:0x140014ea420] /home/relayer []})} between chains penumbraA-0 and penumbraB-0: exit code 2: Res: {Code:0 Log: Info: Index:0 Key:[115 104 105 101 108 100 101 100 95 112 111 111 108 47 97 110 99 104 111 114 47 52] Value:[] ProofOps:ops:<type:"jmt:v" key:"shielded_pool/anchor/4" data:"\022\214\n\n\026shielded_pool/anchor/4\022\253\005\n\035penumbra_consensus_states/0-1\022\200\001\n./ibc.lightclients.tendermint.v1.ConsensusState\022N\n\006\010\350\241\307\251\006\022\"\n J\311\363>.\232\026\305\316\375a*2W\337\276>d\316\010\034{\235\214I]=\302\200\245\305\234\032 gZJ|\315,\342,4=[@\237\311q\211@\000\375\310\022\235}<\267M>5`\244\273H\032\025\010\001\020\001\030\001*\rJMT::LeafNode\"4\010\001\0220JMT::IntrnalNode\217z\003\n^\372k_&4\203\370\030\267B\010\0226\324\212\373\304\027\034\375A\037G\315\375\n\346\"6\010\001\022\020JMT::IntrnalNode\032 SPARSE_MERKLE_PLACEHOLDER_HASH__\"4\010\001\0220JMT::IntrnalNodeSPARSE_MERKLE_PLACEHOLDER_HASH__\"6\010\001\022\020JMT::IntrnalNode\032 SPARSE_MERKLE_PLACEHOLDER_HASH__\"6\010\001\022\020JMT::IntrnalNode\032 \241\320.6\357f\224\374L\315K\207\255b\2602\034\260\255\210C\236jc\023\177\342\333:*\314\215\"4\010\001\0220JMT::IntrnalNode\026\221\333\220\216a\221b\357E\027\235+\327\224~0>Z\367\000\3318_\036eQ\222I\236\371\371\"6\010\001\022\020JMT::IntrnalNode\032 \205O;3\237\326\244\004\312.\312l49#n\353b\302G\333`\322$\311\210\014K\340.3\353\"6\010\001\022\020JMT::IntrnalNode\032 \373?fM\202\353\017\310w\270\262f\320\032\251\3115\232\225V\023$C\201}\213\264T-\313\301\351\"6\010\001\022\020JMT::IntrnalNode\032 'q\253\244\025C.\341\177\350\344\017\246\334\307\212\350\314\220\360\206`\356\227\000\352\346I\001&yN\032\303\004\n\035penumbra_consensus_states/0-8\022\206\001\n./ibc.lightclients.tendermint.v1.ConsensusState\022T\n\014\010\375\241\307\251\006\020\366\377\241\361\001\022\"\n \203>\014.\342\365\253\301\236\333\340n\254\301ds\002\376\023\210\t\\4N\345\010k\323\340\010\276x\032 gZJ|\315,\342,4=[@\237\311q\211@\000\375\310\022\235}<\267M>5`\244\273H\032\025\010\001\020\001\030\001*\rJMT::LeafNode\"6\010\001\022\020JMT::IntrnalNode\032 \333&j\366R\201^\207\364\344tv\363|0\n\233\000bd\005\030\037D\\\tXq\235\253\316\244\"6\010\001\022\020JMT::IntrnalNode\032 f\300\366\364\035\355Z\260\025Z\260\002\005`/\222\311\274G:\3218\341Dh\000\237\316_\030\233j\"4\010\001\0220JMT::IntrnalNodeT\256\000\003pA^\261\021\036\027\310\357\327\020\203y\303_\257K\210\302\014E\030\351\025\204\344\026/\"4\010\001\0220JMT::IntrnalNode\026\221\333\220\216a\221b\357E\027\235+\327\224~0>Z\367\000\3318_\036eQ\222I\236\371\371\"6\010\001\022\020JMT::IntrnalNode\032 \205O;3\237\326\244\004\312.\312l49#n\353b\302G\333`\322$\311\210\014K\340.3\353\"6\010\001\022\020JMT::IntrnalNode\032 \373?fM\202\353\017\310w\270\262f\320\032\251\3115\232\225V\023$C\201}\213\264T-\313\301\351\"6\010\001\022\020JMT::IntrnalNode\032 'q\253\244\025C.\341\177\350\344\017\246\334\307\212\350\314\220\360\206`\356\227\000\352\346I\001&yN" > ops:<type:"apphash" key:"PenumbraAppHash" data:"\n7\n\017PenumbraAppHash\022 \312cB\326\022\341$\217\362\314\0001\263\272\232P\000^\013!m\360h%\307\342\363@]\233+M\032\002\010\001" >  Height:9 Codespace:} 
        	            	 2023-10-20T00:59:48.544000Z	debug	Creating client	{"src_chain_id": "penumbraA-0", "dst_chain_id": "penumbraB-0", "dst_header_height": 9, "trust_period": 7200}
        	            	2023-10-20T00:59:48.544000Z	debug	Creating client	{"src_chain_id": "penumbraB-0", "dst_chain_id": "penumbraA-0", "dst_header_height": 9, "trust_period": 7200}
        	            	2023-10-20T00:59:48.546603Z	debug	No client found on source chain tracking the state of counterparty chain; creating client	{"src_chain_id": "penumbraA-0", "dst_chain_id": "penumbraB-0"}
        	            	2023-10-20T00:59:48.546886Z	debug	No client found on source chain tracking the state of counterparty chain; creating client	{"src_chain_id": "penumbraB-0", "dst_chain_id": "penumbraA-0"}
        	            	panic: runtime error: slice bounds out of range [2:0]
        	            	
        	            	goroutine 54 [running]:
        	            	github.com/cosmos/relayer/v2/relayer/chains/penumbra.(*PenumbraProvider).getAnchor(0x4001346900, {0x33ed720, 0x4001536550})
        	            		/go/relayer/chains/penumbra/tx.go:283 +0x43c
        	            	github.com/cosmos/relayer/v2/relayer/chains/penumbra.(*PenumbraProvider).sendMessagesInner(0x4001346900, {0x33ed720, 0x4001536550}, {0x4000db4f30, 0x1, 0x1}, {0x2530ba0?, 0x4000db4f10?})
        	            		/go/relayer/chains/penumbra/tx.go:334 +0x21c
        	            	github.com/cosmos/relayer/v2/relayer/chains/penumbra.(*PenumbraProvider).SendMessages(0x4001346900, {0x33ed720, 0x4001536550}, {0x4000db4f30, 0x1, 0x1}, {0x4001532240?, 0x2aabac0?})
        	            		/go/relayer/chains/penumbra/tx.go:368 +0x54
        	            	github.com/cosmos/relayer/v2/relayer.CreateClient.func3()
        	            		/go/relayer/client.go:212 +0x64
        	            	github.com/avast/retry-go/v4.Do.func1()
        	            		/root/go/pkg/mod/github.com/avast/retry-go/v4@v4.5.0/retry.go:115 +0x24
        	            	github.com/avast/retry-go/v4.DoWithData[...](0x4001589928?, {0x40014b7ab8, 0x4, 0x10})
        	            		/root/go/pkg/mod/github.com/avast/retry-go/v4@v4.5.0/retry.go:179 +0x550
        	            	github.com/avast/retry-go/v4.Do(0x33ed720?, {0x40014b7ab8?, 0x400129c870?, 0x33f3248?})
        	            		/root/go/pkg/mod/github.com/avast/retry-go/v4@v4.5.0/retry.go:118 +0x4c
        	            	github.com/cosmos/relayer/v2/relayer.CreateClient({0x33ed720, 0x4001536550}, 0x4001536050, 0x4001536230, {0x33cd3c0?, 0x4000d67c80?}, {0x33cd3c0, 0x4000d50450}, 0x1?, 0x1?, ...)
        	            		/go/relayer/client.go:209 +0xbb8
        	            	github.com/cosmos/relayer/v2/relayer.(*Chain).CreateClients.func4()
        	            		/go/relayer/client.go:63 +0x6c
        	            	golang.org/x/sync/errgroup.(*Group).Go.func1()
        	            		/root/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:75 +0x58
        	            	created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        	            		/root/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:72 +
```
</details>

Additionally, adding some ad-hoc logging messages, we see:

<details>
<summary>
empty result.Value
</summary>

```
Shielded Res: {Code:0 Log: Info: Index:0 Key:[115 104 105 101 108 100 101 100 95 112 111 111 108 47 97 110 99 104 111 114 47 56] Value:[] ProofOps:ops:<type:"jmt:v" key:"shielded_pool/anchor/8" data:"\022\204\014\n\026shielded_pool/anchor/8\022\340\005\n\035penumbra_consensus_states/0-4\022\205\001\n./ibc.lightclients.tendermint.v1.ConsensusState\022S\n\013\010\251\323\340\251\006\020\272\234\372Z\022\"\n W1\215\2527X\035\274\025\036\231O\036fN\353/\221(\322\020\272)8@\246\t\316Y\2337]\032 _I\201(\273\032\0039\335\317\010\256\255V\010\254\365H\371\327X\021dnq\260\330\033(4\200r\032\025\010\001\020\001\030\001*\rJMT::LeafNode\"4\010\001\0220JMT::IntrnalNode\377k\275\260\024u\251N\3624[\202\340\261\207i\332\210U\244\\a7\255\225X8'n\336KK\"4\010\001\0220JMT::IntrnalNodeSPARSE_MERKLE_PLACEHOLDER_HASH__\"4\010\001\0220JMT::IntrnalNode\253\023\260R\341%\220\336\\\033tl\256\001\210\346i\344\304\376H\220\377.\300\347\r\211U\360+\247\"6\010\001\022\020JMT::IntrnalNode\032 SPARSE_MERKLE_PLACEHOLDER_HASH__\"4\010\001\0220JMT::IntrnalNodeSPARSE_MERKLE_PLACEHOLDER_HASH__\"4\010\001\0220JMT::IntrnalNode\225\215\3409\303\207\0019\257\r\237\037\263\n\213\334\005 \345UP\026p\246(a\331Xt R\211\"6\010\001\022\020JMT::IntrnalNode\032 F\013\277B\037\322\222\310\367\206\203O\270\027P\272?p\344\362\316\326\233\016\007\r\251\306\352p}H\"4\010\001\0220JMT::IntrnalNode\013\311r\374\034\272\374\315\n\177|\335\345xIs\213\236\027\t\223\326\274\345\030\274\215\030\217\364\nZ\"6\010\001\022\020JMT::IntrnalNode\032 #x\364I\272\353\342y\306\370\304\\\002\026\3442\301\375\327\2700\351lS\036\310$j\272\026\311\324\"4\010\001\0220JMT::IntrnalNode>f\326\251\335\027\347\343\332\244\341\312\315\273\246\347\271$\245{\024\300XQ\236\352\302g\\\315jv\032\206\006\nZstaking/validator/penumbravalid10ehsw5s3h94tekqgx40274mnz60jrz2zvvh8zj3ak5xt5xqnjgqqlcsmah\022\306\002\n\"\n ~o\007R\021\271j\274\330\0105^\257Ws\026\237!\211Bc.qJ=\265\014\272\030\023\222\000\022 \326\331\241\214g{\364G\007\344\344\315Xw\364E\371\r>\374\230\362!\234\371@\240\345N\023\211\204\032\013validator-1\"\023https://validator-1*\027validator-1 description2\232\001\n\227\001\n\222\001penumbrav2t1pdjnulf9klq0345vcngcm65khqzs5qtue2z998jk67rtgpvjvkz6grqgpch486umw6m8mrx8jtdg3xkrra5rtp8udpasldlmufk0fq774e6424p7vcdwngddtq4krkp73pncqz\020d8\001@\001J\"\n ~o\007R\021\271j\274\330\0105^\257Ws\026\237!\211Bc.qJ=\265\014\272\030\023\222\000\032\025\010\001\020\001\030\001*\rJMT::LeafNode\"6\010\001\022\020JMT::IntrnalNode\032 #\023\r\206\312\361\275\002\200\367\270\236\245\3632E\225\007\010\203c\331\365\372\222\3327)\236N\036\317\"6\010\001\022\020JMT::IntrnalNode\032 \202\217cq\317\376\006\201\022J\317\346(\236\213&\342\320F\374*\006\014%P\016\310\225\332\322q\215\"4\010\001\0220JMT::IntrnalNode\275\304I\2728Q\354|3\rY4\354\350\375$e{_\302\317\301o\367|\373\244\023\026]d{\"4\010\001\0220JMT::IntrnalNode\013\311r\374\034\272\374\315\n\177|\335\345xIs\213\236\027\t\223\326\274\345\030\274\215\030\217\364\nZ\"6\010\001\022\020JMT::IntrnalNode\032 #x\364I\272\353\342y\306\370\304\\\002\026\3442\301\375\327\2700\351lS\036\310$j\272\026\311\324\"4\010\001\0220JMT::IntrnalNode>f\326\251\335\027\347\343\332\244\341\312\315\273\246\347\271$\245{\024\300XQ\236\352\302g\\\315jv" > ops:<type:"apphash" key:"PenumbraAppHash" data:"\n7\n\017PenumbraAppHash\022 \023VS\335v\242\243\371,Vy \303\013\007\320\200P\301\031\247Z\035i\\\210z\230\322\357)\264\032\002\010\001" >  Height:9 Codespace:} 
```

**Comment by hdevalence** [comment]
This may be fixed by https://github.com/cosmos/relayer/pull/1355

**Comment by avahowell** [comment]
should be fixed by https://github.com/cosmos/relayer/compare/main...penumbra-zone:relayer:get-anchor-fix

**Comment by avahowell** [comment]
The go relayer is working now, along with interchaintest.
