### ISSUE TITLE
Panic instead of error when sending funds to invalid address

### ISSUE THREAD

**Issue by Valentine1898** [penumbra-zone/penumbra#3332]
When I try to send funds to `penumbra1rtjzkgm553lyqufnr4sp368dp8rajlm2p96hmclld3r4wcqapezraav04xq5849ksq7qf8jvhvv37y4uqxsjv4s684au3vc2g203f8um2f0rwsgm8qjf7anvqgrgdf0safyxsr9` I get panic, even though I expect to get an invalid address error.

Related issue on web repo: https://github.com/penumbra-zone/web/issues/232

I sent this address to faucet channel and it seems to have broken it for a while 

```
thread 'main' panicked at crates/core/transaction/src/plan/clue.rs:33:64:
valid address: InvalidAddress
stack backtrace:
   0: rust_begin_unwind
             at /rustc/75b064d26970ca8e7a487072f51835ebb057d575/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/75b064d26970ca8e7a487072f51835ebb057d575/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/75b064d26970ca8e7a487072f51835ebb057d575/library/core/src/result.rs:1653:5
   3: penumbra_transaction::plan::clue::CluePlan::clue
   4: penumbra_transaction::effect_hash::<impl penumbra_transaction::plan::TransactionPlan>::effect_hash
   5: penumbra_transaction::plan::auth::<impl penumbra_transaction::plan::TransactionPlan>::authorize
   6: penumbra_custody::soft_kms::SoftKms::sign
   7: <penumbra_custody::soft_kms::SoftKms as penumbra_proto::penumbra::custody::v1alpha1::custody_protocol_service_server::CustodyProtocolService>::authorize::{{closure}}
   8: <<penumbra_proto::penumbra::custody::v1alpha1::custody_protocol_service_server::CustodyProtocolServiceServer<T> as tower_service::Service<http::request::Request<B>>>::call::AuthorizeSvc<T> as tonic::server::service::UnaryService<penumbra_proto::penumbra::custody::v1alpha1::AuthorizeRequest>>::call::{{closure}}
   9: <penumbra_proto::penumbra::custody::v1alpha1::custody_protocol_service_server::CustodyProtocolServiceServer<T> as tower_service::Service<http::request::Request<B>>>::call::{{closure}}
  10: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  11: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  12: <penumbra_proto::penumbra::custody::v1alpha1::custody_protocol_service_client::CustodyProtocolServiceClient<T> as penumbra_custody::client::CustodyClient>::authorize::{{closure}}
  13: pcli::network::<impl pcli::App>::build_transaction::{{closure}}
  14: pcli::network::<impl pcli::App>::build_and_submit_transaction::{{closure}}
  15: pcli::command::tx::TxCmd::exec::{{closure}}
  16: pcli::main::{{closure}}
  17: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  18: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
  19: tokio::runtime::context::runtime::enter_runtime
  20: tokio::runtime::runtime::Runtime::block_on
  21: pcli::main

```

**Comment by grod220** [comment]
Ah, it seems the panic in the web code is caused by this line:

https://github.com/penumbra-zone/penumbra/blob/main/crates/core/transaction/src/plan/clue.rs#L33

We essentially are unwrapping instead of handling a Result type
