### ISSUE TITLE
Guide instructions for metrics don't work

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#4565]
**Describe the bug**

Running `just metrics` gives
```
Attaching to grafana-1, prom-1
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: Mounts denied:
The path /home/conor/src/penumbra/deployments/config/prometheus.yml is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
error: Recipe `metrics` failed on line 3 with exit code 1
```

After editing the file, metrics start but navigating to `http://localhost:3000` doesn't open grafana.

**Comment by conorsch** [comment]
There was definitely a hardcoded path in there, easy enough to fix. But there's a tension here for a smooth dev env, between docker tooling and hetereogenous tooling. 

This patch ostensibly should land:

```diff
diff --git a/deployments/compose/metrics.yml b/deployments/compose/metrics.yml
index 5121cb15a..9b2e391ae 100644
--- a/deployments/compose/metrics.yml
+++ b/deployments/compose/metrics.yml
@@ -13,11 +13,17 @@ services:
       dockerfile: deployments/containerfiles/Dockerfile-grafana
     network_mode: host
     user: "${UID:-1000}"
+    # Don't use ports, since ports conflicts with network_mode=host.
+    # We use network_mode=host so that metrics can talk to services bound
+    # to localhost.
+    # ports:
+    #   - "3000:3000"

   # The Prometheus service, for scraping metrics from Penumbra's pd metrics port.
   prom:
     image: "docker.io/prom/prometheus"
     network_mode: host
+    # ports:
+    #   - "9090:9090"
     volumes:
-      # TODO: this path is not accurate
-      - /home/conor/src/penumbra/deployments/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
+      - "${PWD:?}/../config/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
diff --git a/deployments/config/prometheus.yml b/deployments/config/prometheus.yml
index b19d6a424..1a6b08175 100644
--- a/deployments/config/prometheus.yml
+++ b/deployments/config/prometheus.yml
@@ -1,5 +1,5 @@
 scrape_configs:
-  - job_name: 'Tendermint Node'
+  - job_name: 'CometBFT Node'
     scrape_interval: 10s
     scheme: http
     metrics_path: metrics
```

because it's better than the state of current man, but unfortunately [the host_network option is only relevant for Linux hosts](https://docs.docker.com/network/drivers/host/), so that's a no-go as a happy-path on dev env: we need mac support as first-class. Shortest path is just to use port-forwarding on the metrics networking, accepting the downside that one must run pd & cometbft also via compose in order for everything to talk together. That seems a reasonable compromise for a clean first-run experience.

Medium-term, I'd like to move away from using the containers locally, because they're a pain particularly on mac, and lean into process composition via e.g. nix/devbox. Punting on that for now, but we do already have a solid start to nix compat thanks to @cratelyn and @plaidfinch.

**Comment by hdevalence** [comment]
@conorsch awesome, thanks for looking into this, that's helpful info!

> because it's better than the state of current man, but unfortunately [the host_network option is only relevant for Linux hosts](https://docs.docker.com/network/drivers/host/), so that's a no-go as a happy-path on dev env: we need mac support as first-class

It seems like there's an assumption here that we have to have one canonical set of configs, but I'm not sure if this is necessarily the case?

That would definitely be desirable if we thought of the `deployments/` as being the literal deployment scripts of a particular service. But here we're writing software for the community to run, so there isn't really a canonical deployment, and I think it makes sense to have the contents of the `deployments/` be example configs that people may be able to run off-the-shelf or may use as a basis for their own deployments. From that point of view, couldn't we just change the docs for metrics to have pointers to different platform-specific configs?

**Comment by hdevalence** [comment]
Running on linux (with the changed config file path) gives:
```
Recreating compose_grafana_1 ...
Recreating compose_prom_1    ...

ERROR: for compose_prom_1  'ContainerConfig'

ERROR: for compose_grafana_1  'ContainerConfig'

ERROR: for prom  'ContainerConfig'

ERROR: for grafana  'ContainerConfig'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
                ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 579, in execute_convergence_plan
    return self._execute_convergence_recreate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 494, in recreate
    return self.recreate_container(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 612, in recreate_container
    new_container = self.create_container(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 921, in _get_container_create_options
    container_options, override_options = self._build_container_volume_options(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 960, in _build_container_volume_options
    binds, affinity = merge_volume_bindings(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1548, in merge_volume_bindings
    old_volumes, old_mounts = get_container_data_volumes(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1579, in get_container_data_volumes
    container.image_config['ContainerConfig'].get('Volumes') or {}
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'ContainerConfig'
error: Recipe `metrics` failed on line 3 with exit code 1
```
