### ISSUE TITLE
Integer underflow updating token supplies in undelegation processing

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/penumbra#583]
**Describe the bug**

The Orthosie testnet halted because of an integer underflow:
```
Apr 09 12:08:38.655  INFO abci:EndBlock{height=370799}: pd::components::validator_set: crossed epoch boundary, processing rate updates prev_epoch=Epoch { index: 617, duration: 600 } current_epoch=Epoch { index: 618, duration: 600 } next_epoch=Epoch { index: 619, duration: 600 }
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /usr/src/pd/src/components/validator_set.rs:659:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'worker error??: RecvError(())', pd/src/consensus/service.rs:55:34
```
The relevant part of the code is no longer active (it's in the legacy `validator_set.rs`, not the new `staking.rs` code):
```rust
            } else {
                // net undelegation: add the unbonded amount to the staking token supply
                staking_token_supply = staking_token_supply.checked_add(unbonded_amount).unwrap();
                delegation_token_supply = delegation_token_supply
                    .checked_sub(delegation_amount)
                    .unwrap();
            }
```
but the underlying problem may still be present in the new code.

**Additional context**

Without doing a detailed examination, I have a suspicion that this problem is related to the fact that computing delegations and undelegations don't commute with each other, due to rounding.  I suspect (without checking) that this might be happening in a case where someone delegates some stake to a new validator, then undelegates all of their tokens.  This should result in a token supply of 0 delegation tokens, but if we're computing in the "wrong direction" we could be rounding incorrectly (e.g., recomputing the delegation token amount from the undelegation amount, or something, causing us to do a round trip and introducing rounding errors).

**Comment by hdevalence** [comment]
Assigned to Philophyrosyne (testnet 8) rather than Herse (testnet 7), since I don't think we should block on fixing it; if the problem recurs, we could either apply a hot-fix or do Philophyrosyne early.

**Comment by hdevalence** [comment]
I've tried reproducing this by trying to undelegate the entire amount, but it seems that the new staking code is actually doing the rounding correctly. Closing this for now.
